config/routes.rb
AboutP::Application.routes.draw do
  resources :users, except: [:destroy] do
    get 'search', :on => :collection
  end

  root :to => "users#index"
  match "/auth/github/callback", to: "sessions#callback", via: 'get'
  match "/signin", to: "sessions#new", via: 'get'
  match "/signout", to: "sessions#destroy", via: 'delete'
end

app/models/api_key.rb
require 'bcrypt'

class APIKey < Settingslogic
  source "#{Rails.root}/config/hashed_api_key.yml"

  def self.authenticate(api_key)
    BCrypt::Password.new(self[Rails.env]) == api_key
  end
end

app/models/github_member.rb
class GithubMember

  class << self
    def all
      JSON.parse(open("#{Rails.root}/tmp/ppb_members.json").read)
    end

    def paperboy?(nickname)
      self.all.has_key? nickname
    end
  end

end

app/models/github_tokens.rb
class GithubTokens < Settingslogic
  source "#{Rails.root}/config/github_tokens.yml"
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :users
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  include AboutP::Utils
  extend Enumerize

  belongs_to :section
  validates :name, presence: true, length: { maximum: 40 }
  validates :section_id, presence: true
  validates :job_type, presence: true
  validates :github_uid, presence: true
  validates :irc_name, presence: true, length: { maximum: 20 }, format: { with: /\A[a-zA-Z][a-zA-Z\-\_\^0-9]*\Z/ }, uniqueness: { case_sensitive: false }
  validates :twitter_id, length: { maximum: 15 }, format: { with: /\A[0-9a-zA-Z\_]*\Z/ }

  before_save :create_remember_token
  after_create :notify_newcomer, :if => ->{ Rails.env.production? }
  after_update :notify_update, :if => ->{ Rails.env.production? }

  private
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end

  def notify_newcomer
    ikachan("#{self.nickname} さんがabout pをはじめました: http://about-p-kitak.sqale.jp/users/#{self.id}")
  end

  def notify_update
    ikachan("#{self.nickname} さんがabout pのプロフィールを更新しました: http://about-p-kitak.sqale.jp/users/#{self.id}")
  end

  enumerize :job_type, :in => [:engineer, :designer, :director, :customer_service, :backoffice, :producer, :manager, :officer, :other]

  mount_uploader :face_image, FaceImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :already_login, only: [:new]

  def new
  end

  def callback
    auth = request.env["omniauth.auth"]
    unless GithubMember.paperboy? auth["info"]["nickname"]
      redirect_to signin_path
      return
    end

    user = User.find_by(github_uid: auth["uid"])
    if user
      sign_in user
      flash[:success] = "aboutPへようこそ"
      redirect_to users_path
    else
      session[:github_uid] = auth["uid"]
      session[:github_nickname] = auth["info"]["nickname"]
      redirect_to new_user_path
    end
  end

  def destroy
    sign_out
    redirect_to signin_path
  end

  private
  def already_login
    redirect_to users_path if signed_in?
  end
end

app/controllers/users_controller.rb
# -*- coding: utf-8 -*-
class UsersController < ApplicationController
  before_action :halfway_creation, except: [:new, :create]
  before_action :ppb_member, only: [:new, :create]
  before_action :no_signed_in_user, only: [:new, :create]
  before_action :through_github, only: [:new, :create]
  before_action :signed_in_user, only: [:index, :edit, :update, :destroy, :show]
  before_action :correct_user, only: [:edit, :update]
  before_action :api_key, only: [:search]

  def index
    @sections = Section.all
  end

  def new
    @sections = Section.all
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find_by(nickname: params[:id]) || User.find(params[:id])
  end

  def create
    @section = Section.find_by(id: params[:user][:section])
    @user = @section.users.build(user_params)
    @user.github_uid = session[:github_uid]
    @user.github_name = session[:github_nickname]
    if @user.save
      sign_in @user
      flash[:success] = "aboutPへようこそ"
      session[:github_uid] = nil
      session[:github_nickname] = nil
      session[:realname] = nil
      redirect_to users_path
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
    @user.section = Section.find_by(id: params[:user][:section])
    if @user.update_attributes(user_params)
      sign_in @user
      flash[:success] = "プロフィールを更新しました"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def search
    query_value = "#{params[:query]}%"
    columns = [:name, :nickname, :irc_name, :github_name]
    where_statement =
      columns.map { |column|
        "#{column} like ?"
      }.join(' or ')
    users = User.where(where_statement, *(Array.new(4) { query_value }))
                .map { |user| user.slice(*columns) }
    render :json => users
  end

  private

  def user_params
    params.require(:user).permit(:name, :nickname, :irc_name, :face_image, :job_type,  :birthday, :birthplace, :married, :background, :ppb_join, :ppb_carrier, :hometown, :twitter_id, :blog_url, :hobby, :favorite_food, :favorite_book, :club, :strong_point, :free_space)
  end
  # Before actions

  def signed_in_user
    redirect_to signin_url, notice: "サインインしてください" unless signed_in?
  end

  def no_signed_in_user
    redirect_to users_path if signed_in?
  end

  def ppb_member
    if GithubMember.paperboy? session[:github_nickname]
      session[:realname] = GithubMember.all[session[:github_nickname]]
    else
      flash[:error] = "ペパボの人じゃないひとは入れません！"
      redirect_to signin_path
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(users_path) unless current_user?(@user)
  end

  def halfway_creation
    user = User.find_by(github_uid: session[:github_uid])
    redirect_to(new_user_path) if session[:github_uid] != nil && user == nil
  end

  def through_github
    redirect_to(signin_path) unless session[:github_uid]
  end

  def api_key
    api_key = request.env["HTTP_X_ABOUTP_API_KEY"]
    unless api_key && APIKey.authenticate(api_key)
      render :status => 403, :nothing => true
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "about p"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    params[:github_uid] = nil
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by(remember_token: cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>about p</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% unless request.path_info == signin_path %>
  <header>
    <div class="wrap">
    <%= link_to(content_tag(:div, "", :class => 'logo'), users_path) if request.path_info != signin_path %>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "alert alert-#{key}") %>
    <% end %>
    <div id="menu">
      <ul>
    <% if signed_in? %>
      <% if current_user.face_image_url(:header_thumb).to_s.empty? %>
      <li><%= link_to(image_tag("dummy_img40.gif", size: "40x40"), user_path(current_user)) %><%= link_to(current_user.name, user_path(current_user)) %></li>
      <% else %>
      <li><%= link_to(image_tag(current_user.face_image_url(:header_thumb).to_s, size: "40x40"), user_path(current_user)) %><%= link_to(current_user.name, user_path(current_user)) %></li>
      <% end %>
      <li><%= link_to "みんな", users_path %></li>
      <li><%= link_to "自分のプロフィール", user_path(current_user) %></li>
      <li><%= link_to "サインアウト", signout_path, method: "delete" %></li>
    <% end %>
  </ul>
  </div>
  </div>
  </header>
  <% end %>
<div id="content">
<%= yield %>
</div>
<footer>
  <p>Copyright ©2013  GMO Pepabo, Inc. All Rights Reserved.</p>
  </footer>
</body>
</html>

app/views/users/edit.html.erb
<div id="edit">
<%= form_for(@user, :html => {:multipart => true}) do |f| %>
  <% if f.object.errors.any? %>
    <div class="error">
      <% f.object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </div>
  <% end %>
    <div class="pro_img">
<% %>
      <% if @user.face_image_url(:profile_thumb).to_s.empty? %>
      <%= image_tag "dummy_img180.gif", :width => "180" %>
      <% else %>
      <%= image_tag @user.face_image_url(:profile_thumb).to_s, :width => "180" %>
      <% end %>
        <%= f.file_field :face_image %>
    <p class="btn_edit_submit"><%= f.submit %></p>
  </div>
  <div class="pro_text">
    <p class="aori">基本情報<span class="nes_notice">*青文字は必須項目です</span></p>
  <ul>
    <li><span class="nes"><%= f.label :name %></span><%= f.text_field :name %></li>
    <li><span class="nes"><%= f.label :nickname %></span><%= f.text_field :nickname %></li>
    <li><span class="nes"><%= f.label :irc_name %></span><%= f.text_field :irc_name %></li>
    <li><span class="nes"><%= f.label :section %></span><%= f.select :section, Section.all.map { |item| [item.name, item.id] }, :selected => @user.section.id %></li>
    <li><span class="nes"><%= f.label :job_type %></span><%= f.select :job_type, User.job_type.options %></li>
    <li><span class="nes"><%= f.label :birthday %></span><%= f.date_select :birthday, :use_month_numbers => true, :date_separator => '/', :start_year => 1950, :end_year => Time.now.year-14 %></li>
    <li><%= f.label :birthplace %><%= f.text_field :birthplace %></li>
    </ul>
    <p class="aori">あなたのことをもっと教えて</p>
<ul class="long">
    <li><%= f.label :married %><%= f.text_area :married %></li>
    <li><p><%= f.label :background %></p><%= f.text_area :background %></li>
    <li><p><%= f.label :ppb_join %></p><%= f.text_area :ppb_join %></li>
    <li><p><%= f.label :ppb_carrier %></p><%= f.text_area :ppb_carrier %></li>
    <li><p><%= f.label :hometown %></p><%= f.text_area :hometown %></li>
    <li><p><%= f.label :twitter_id %></p><%= f.text_area :twitter_id %></li>
    <li><p><%= f.label :blog_url %></p><%= f.text_area :blog_url %></li>
    <li><p><%= f.label :hobby %></p><%= f.text_area :hobby %></li>
    <li><p><%= f.label :favorite_food %></p><%= f.text_area :favorite_food %></li>
    <li><p><%= f.label :favorite_book %></p><%= f.text_area :favorite_book %></li>
    <li><p><%= f.label :club %></p><%= f.text_area :club %></li>
    <li><p><%= f.label :strong_point %></p><%= f.text_area :strong_point %></li>
    <li><p><%= f.label :free_space %></p><%= f.text_area :free_space %></li>
  </ul>
<% end %>
</div>
</div>

app/views/users/index.html.erb
<p class="total_number"><%= @total_number %></p>
<h2>みんな</h2>
<div class="everyone">
  <% @sections.each do |section| %>
    <div class="section_box">
      <p class="section_name"><%= section.name %></p>
      <ul>
        <% section.users.each do |user| %>
          <% if user.face_image_url(:index_thumb).to_s.empty? %>

            <li><%= link_to(image_tag("dummy_img60.gif", :size => "60x60"), user_path(user)) %><%= link_to user.name, user %></li>
          <% else %>
            <li><%= link_to(image_tag(user.face_image_url(:index_thumb).to_s, :size => "60x60"), user_path(user)) %><%= link_to user.name, user %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div id="edit">
<%= form_for(@user, :html => {:multipart => true}) do |f| %>
  <% if f.object.errors.any? %>
    <div class="error">
      <% f.object.errors.full_messages.each do |msg| %>
        <li>* <%= msg %></li>
      <% end %>
    </div>
  <% end %>
    <div class="pro_img">
      <p>顔写真を設定してね！</p>
      <%= image_tag "dummy_img2.png" %>
      <%= f.file_field :face_image %>
    <p class="btn_edit_submit"><%= f.submit %></p>
  </div>
  <div class="pro_text">
    <p class="aori">基本情報<span class="nes_notice">*青文字は必須項目です</span></p>
  <ul>
    <li><span class="nes"><%= f.label :name %></span><%= f.text_field :name, :value => session[:realname] %></li>
    <li><span class="nes"><%= f.label :nickname %></span><%= f.text_field :nickname, :value => session[:github_nickname] %></li>
    <li><span class="nes"><%= f.label :irc_name %></span><%= f.text_field :irc_name %></li>
    <li><span class="nes"><%= f.label :section %></span><%= f.select :section, Section.all.map { |item| [item.name, item.id] } %></li>
    <li><span class="nes"><%= f.label :job_type %></span><%= f.select :job_type, User.job_type.options %></li>
    <li><span class="nes"><%= f.label :birthday %></span><%= f.date_select :birthday, :use_month_numbers => true, :date_separator => '/', :start_year => 1950, :end_year => Time.now.year-14, :default => Date.new(1980,01,01) %></li>
    <li><%= f.label :birthplace %><%= f.text_field :birthplace %></li>
    </ul>
    <ul class="long">
    <li><p><%= f.label :ppb_join %></p><%= f.text_area :ppb_join %></li>
    <li><p><%= f.label :ppb_carrier %></p><%= f.text_area :ppb_carrier %></li>
    <li><p><%= f.label :hometown %></p><%= f.text_area :hometown %></li>
    <li><p><%= f.label :twitter_id %></p><%= f.text_area :twitter_id %></li>
    <li><p><%= f.label :blog_url %></p><%= f.text_area :blog_url %></li>
    <li><p><%= f.label :hobby %></p><%= f.text_area :hobby %></li>
     <li><p><%= f.label :strong_point %></p><%= f.text_area :strong_point %></li>
    <li><p><%= f.label :free_space %></p><%= f.text_area :free_space %></li>
  </ul>
<% end %>
</div>
</div>

app/views/users/show.html.erb
<div id="profile">
  <% if request.path_info == user_path(current_user) %>
    <p><%= link_to "プロフィールを編集", edit_user_path(current_user) %></p>
  <% end %>
  <div class="pro_img">
    <% if @user.face_image_url(:profile_thumb).to_s.empty? %>
      <%= image_tag 'dummy_img180.gif', :width => "180" %>
    <% else %>
      <%= image_tag @user.face_image_url(:profile_thumb).to_s, :width => "180" %>
    <% end %>
  </div>

<div class="pro_text">
<li><span><%= t("activerecord.attributes.user.name") %></span><%= @user.name %></li>
<li><span><%= t("activerecord.attributes.user.nickname") %></span><%= @user.nickname %></li>
<li><span><%= t("activerecord.attributes.user.irc_name") %></span><%= @user.irc_name %></li>
<li><span><%= t("activerecord.attributes.user.github_name") %></span><%= @user.github_name %></li>
<li><span><%= t("activerecord.attributes.user.section") %></span><%= @user.section.name %></li>
<li><span><%= t("activerecord.attributes.user.job_type") %></span><%= @user.job_type_text %></li>
<li><span><%= t("activerecord.attributes.user.birthday") %></span><%= @user.birthday %></li>
<% if @user.birthplace.present? %>
<li><span><%= t("activerecord.attributes.user.birthplace") %></span><%= @user.birthplace %></li>
<% end %>
<% if @user.married.present? %>
<li><span><%= t("activerecord.attributes.user.married") %></span><%= simple_format(@user.married) %></li>
<% end %>
<% if @user.background.present? %>
<li><p class="q"><%= t("activerecord.attributes.user.background") %></p><%= simple_format(@user.background) %></li>
<% end %>
<% if @user.ppb_join.present? %>
<li><p class="q"><%= t("activerecord.attributes.user.ppb_join") %></p><%= simple_format(@user.ppb_join) %></li>
<% end %>
<% if @user.ppb_carrier.present? %>
<li><p class="q"><%= t("activerecord.attributes.user.ppb_carrier") %></p><%= simple_format(@user.ppb_carrier) %></li>
<% end %>
<% if @user.hometown.present? %>
<li><p class="q"><%= t("activerecord.attributes.user.hometown") %></p><%= simple_format(@user.hometown) %></li>
<% end %>
<% if @user.twitter_id.present? %>
<li><p class="q"><%= t("activerecord.attributes.user.twitter_id") %></p><%= @user.twitter_id %></li>
<% end %>
<% if @user.blog_url.present? %>
<li><p class="q"><%= t("activerecord.attributes.user.blog_url") %></p><%= link_to(@user.blog_url, @user.blog_url, target: "_blank") %></li>
<% end %>
<% if @user.hobby.present? %>
<li><p class="q"><%= t("activerecord.attributes.user.hobby") %></p><%= simple_format(@user.hobby) %></li>
<% end %>
<% if @user.favorite_food.present? %>
<li><p class="q"><%= t("activerecord.attributes.user.favorite_food") %></p><%= simple_format(@user.favorite_food) %></li>
<% end %>
<% if @user.favorite_book.present? %>
<li><p class="q"><%= t("activerecord.attributes.user.favorite_book") %></p><%= simple_format(@user.favorite_book) %></li>
<% end %>
<% if @user.club.present? %>
<li><p class="q"><%= t("activerecord.attributes.user.club") %></p><%= simple_format(@user.club) %></li>
<% end %>
<% if @user.strong_point.present? %>
<li><p class="q"><%= t("activerecord.attributes.user.strong_point") %></p><%= simple_format(@user.strong_point) %></li>
<% end %>
<% if @user.free_space.present? %>
<li><p class="q"><%= t("activerecord.attributes.user.free_space") %></p><%= simple_format(@user.free_space) %></li>
<% end %>
</div>
</div>